
### New Product
POST http://localhost:5031/product
Content-Type: application/json

{
    "name": "Product 1",
    "price": 10.00,
    "categoryId": "0ae8ed84-3ca0-4abd-a494-70e00ba238b3"
}

### Get Products
GET http://localhost:5031/products

### Get Product by Id
GET http://localhost:5031/products/861c0859-beac-49d6-8e77-3af7b3db5ce6

### Remove Product
DELETE http://localhost:5031/product/d18f5a6d-42e7-4bdf-9996-830ccd90b0c2